### ISSUE TITLE
ca not receive

### ISSUE THREAD

**Issue by wettermann32** [alpha-hacks/alpha-bluetooth#1]
Hi David,

thanks for this Code. I was able to send some commands. Anyhow receiving i just get Errors. The return is always that the Robot is disconnected. Is it working with your Robot?

Thanks Michael

you ar able to start a hts-file on your Robot?

**Comment by wettermann32** [comment]
Found the problem. Solved with setting the port to 6 instead of 1

**Comment by davidsanfal** [comment]
Hi @wettermann32!

I haven't had much time the last months, so thanks for the bugfix, I had the same problem.

You can make a pull request with this change if you want to contribute to the project or I can add it if you don't want to do that.

thanks!!

[HowTo: Contributing to open source project](https://guides.github.com/activities/contributing-to-open-source/)

**Comment by wettermann32** [comment]
Hi David,

i am not really familiar with github. So I would appreciate if you could 
add it.

Regards Michael

Am 19.12.2016 um 23:38 schrieb David Sánchez Falero:

**Comment by davidsanfal** [comment]
Hi  @wettermann32,

I just added the new port number and an example to read the battery. Now you can see this output

```
b'\xfb\xbf\x06\x18\x00\x1e\xed'
searching ...
found 1 devices
Connected
Sent data
b'\xfb\xbf\t\x18\x1c \x00(\x85\xed'
{'voltage': 7200, 'charge': 'no', 'capacity': 40}
```
I'm going to close this issue because it's solved.

Thanks for fix it!
